@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as addressBookLogic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as addressBookStorage STORAGE_COLOR

user -[USER_COLOR]> ui : "delete 1"
activate ui UI_COLOR

ui -[UI_COLOR]> addressBookLogic : execute("delete 1")
activate addressBookLogic LOGIC_COLOR

addressBookLogic -[LOGIC_COLOR]> model : deletePerson(p)
activate model MODEL_COLOR

model -[MODEL_COLOR]-> addressBookLogic
deactivate model

addressBookLogic -[LOGIC_COLOR]> addressBookStorage : saveAddressBook(addressBook)
activate addressBookStorage STORAGE_COLOR

addressBookStorage -[STORAGE_COLOR]> addressBookStorage : Save to file
activate addressBookStorage STORAGE_COLOR_T1
deactivate addressBookStorage

addressBookStorage --[STORAGE_COLOR]> addressBookLogic
deactivate addressBookStorage

addressBookLogic --[LOGIC_COLOR]> ui
deactivate addressBookLogic

ui--[UI_COLOR]> user
deactivate ui
@enduml
